[workspace]
authors = ["Tuatini <email@tuatini.me>"]
channels = ["https://prefix.dev/conda-forge"]
name = "lerobot"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
cmake = ">=3.29.0"
datasets = ">=2.19.0"
deepdiff = ">=7.0.1"
diffusers = ">=0.27.2"
einops = ">=0.8.0"
flask = ">=3.0.3"
gdown = ">=5.1.0"
gymnasium = "=0.29.1"
h5py = ">=3.10.0"
imageio = ">=2.34.0"
jsonlines = ">=4.0.0"
numba = ">=0.59.0"
omegaconf = ">=2.3.0"
opencv = ">=4.9.0"
packaging = ">=24.2"
av = ">=14.2.0"
pymunk = ">=6.6.0"
pynput = ">=1.8.1,<2"
pyzmq = ">=26.2.1"
rerun-sdk = ">=0.23.3,<0.24"
termcolor = ">=2.4.0"
torchvision = ">=0.21.0"
wandb = ">=0.16.3"
zarr = ">=2.17.0"
ruff = ">=0.11.11,<0.12"
click = ">=8.2.1,<9"
ffmpeg-python = ">=0.2.0"
pytest = ">=8.3.5,<9"
huggingface_hub = ">=0.31.4,<0.33"
scipy = ">=1.15.2,<2"
transformers = ">=4.52.4,<5"
accelerate = ">=1.8.0,<2"

[pypi-dependencies]
draccus = "==0.10.0"
torchcodec = ">=0.4.0, <0.5"
feetech-servo-sdk = ">=1.0.0"
num2words = ">=0.5.14, <0.6"

[system-requirements]
cuda = "12.0"

[target.linux-64.dependencies]
cuda-version = "12.6.*"
pytorch-gpu = "*"

[target.osx-arm64.dependencies]
pytorch-cpu = "*"

